version: '3.9'
services:
  backend:
    build: ./back
    container_name: spring-api
    ports:
      - "8080:8080"
    networks:
      - app-net

  frontend:
    build: ./front
    container_name: vite-front
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
